package view;


import java.awt.Color;
import javax.imageio.ImageIO;
import javax.swing.DefaultListModel;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;
import model.*;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author informatica
 */
public class TelaDetalheOnibus extends javax.swing.JFrame implements IDetalheRota{

    /**
     * Creates new form Principal
     */
    public TelaDetalheOnibus() {
        initComponents();
        geraImgArrayAssentos();
        RotaIndexControler ind = new RotaIndexControler();
        int index = RotaIndexControler.getIndex();
        jLabelOrigem.setText(Repositorio.getRotas().get(index).getOrigem());
        jLabelDestino.setText(Repositorio.getRotas().get(index).getDestino());
        jLabelHora.setText(Repositorio.getRotas().get(index).getHora());
        jLabelQtd.setText(""+Repositorio.getRotas().get(index).qtdVagas());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jPanelWithBackground1 = new view.JPanelWithBackground("C:/Users/Jeferson/Documents/NetBeansProjects/GetBus/src/view/bg_detalhesrota.png");//("C:/Documents and Settings/informatica/Meus documentos/NetBeansProjects/GetBus/src/view/bg_inicio.png");
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButtonAssento4 = new javax.swing.JButton();
        jButtonAssento3 = new javax.swing.JButton();
        jButtonAssento7 = new javax.swing.JButton();
        jButtonAssento8 = new javax.swing.JButton();
        jButtonAssento15 = new javax.swing.JButton();
        jButtonAssento16 = new javax.swing.JButton();
        jButtonAssento11 = new javax.swing.JButton();
        jButtonAssento12 = new javax.swing.JButton();
        jButtonAssento31 = new javax.swing.JButton();
        jButtonAssento27 = new javax.swing.JButton();
        jButtonAssento32 = new javax.swing.JButton();
        jButtonAssento28 = new javax.swing.JButton();
        jButtonAssento23 = new javax.swing.JButton();
        jButtonAssento24 = new javax.swing.JButton();
        jButtonAssento20 = new javax.swing.JButton();
        jButtonAssento19 = new javax.swing.JButton();
        jButtonAssento39 = new javax.swing.JButton();
        jButtonAssento40 = new javax.swing.JButton();
        jButtonAssento36 = new javax.swing.JButton();
        jButtonAssento35 = new javax.swing.JButton();
        jButtonAssento2 = new javax.swing.JButton();
        jButtonAssento1 = new javax.swing.JButton();
        jButtonAssento5 = new javax.swing.JButton();
        jButtonAssento6 = new javax.swing.JButton();
        jButtonAssento10 = new javax.swing.JButton();
        jButtonAssento9 = new javax.swing.JButton();
        jButtonAssento13 = new javax.swing.JButton();
        jButtonAssento14 = new javax.swing.JButton();
        jButtonAssento18 = new javax.swing.JButton();
        jButtonAssento17 = new javax.swing.JButton();
        jButtonAssento21 = new javax.swing.JButton();
        jButtonAssento22 = new javax.swing.JButton();
        jButtonAssento26 = new javax.swing.JButton();
        jButtonAssento25 = new javax.swing.JButton();
        jButtonAssento29 = new javax.swing.JButton();
        jButtonAssento30 = new javax.swing.JButton();
        jButtonAssento34 = new javax.swing.JButton();
        jButtonAssento33 = new javax.swing.JButton();
        jButtonAssento37 = new javax.swing.JButton();
        jButtonAssento38 = new javax.swing.JButton();
        jLabelOrigem = new javax.swing.JLabel();
        jLabelDestino = new javax.swing.JLabel();
        jLabelHora = new javax.swing.JLabel();
        jLabelQtd = new javax.swing.JLabel();
        jButtonVoltarPrincipal = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();

        jMenu1.setText("jMenu1");

        jMenu2.setText("jMenu2");

        jMenuItem1.setText("jMenuItem1");

        jMenuItem3.setText("jMenuItem3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("GetBus - Detalhe Rota");
        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(800, 500));
        setResizable(false);

        jPanelWithBackground1.setMaximumSize(new java.awt.Dimension(800, 500));
        jPanelWithBackground1.setMinimumSize(new java.awt.Dimension(800, 500));
        jPanelWithBackground1.setPreferredSize(new java.awt.Dimension(800, 500));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/title_origem.png"))); // NOI18N

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/title_destino.png"))); // NOI18N

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/title_hora.png"))); // NOI18N

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/title_vagas.png"))); // NOI18N

        jButtonAssento4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonAssento4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonAssento4MouseClicked(evt);
            }
        });

        jButtonAssento3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonAssento3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonAssento3MouseClicked(evt);
            }
        });

        jButtonAssento7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonAssento7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonAssento7MouseClicked(evt);
            }
        });

        jButtonAssento8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonAssento8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonAssento8MouseClicked(evt);
            }
        });

        jButtonAssento15.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonAssento15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonAssento15MouseClicked(evt);
            }
        });

        jButtonAssento16.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonAssento16.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonAssento16MouseClicked(evt);
            }
        });

        jButtonAssento11.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonAssento11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonAssento11MouseClicked(evt);
            }
        });

        jButtonAssento12.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonAssento12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonAssento12MouseClicked(evt);
            }
        });

        jButtonAssento31.setToolTipText("");
        jButtonAssento31.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonAssento31.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonAssento31MouseClicked(evt);
            }
        });

        jButtonAssento27.setToolTipText("");
        jButtonAssento27.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonAssento27.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonAssento27MouseClicked(evt);
            }
        });

        jButtonAssento32.setToolTipText("");
        jButtonAssento32.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonAssento32.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonAssento32MouseClicked(evt);
            }
        });

        jButtonAssento28.setToolTipText("");
        jButtonAssento28.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonAssento28.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonAssento28MouseClicked(evt);
            }
        });

        jButtonAssento23.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonAssento23.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonAssento23MouseClicked(evt);
            }
        });

        jButtonAssento24.setToolTipText("");
        jButtonAssento24.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonAssento24.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonAssento24MouseClicked(evt);
            }
        });

        jButtonAssento20.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonAssento20.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonAssento20MouseClicked(evt);
            }
        });

        jButtonAssento19.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonAssento19.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonAssento19MouseClicked(evt);
            }
        });

        jButtonAssento39.setToolTipText("");
        jButtonAssento39.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonAssento39.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonAssento39MouseClicked(evt);
            }
        });

        jButtonAssento40.setToolTipText("");
        jButtonAssento40.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonAssento40.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonAssento40MouseClicked(evt);
            }
        });

        jButtonAssento36.setToolTipText("");
        jButtonAssento36.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonAssento36.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonAssento36MouseClicked(evt);
            }
        });

        jButtonAssento35.setToolTipText("");
        jButtonAssento35.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonAssento35.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonAssento35MouseClicked(evt);
            }
        });

        jButtonAssento2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonAssento2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonAssento2MouseClicked(evt);
            }
        });

        jButtonAssento1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/bg_ass_livre_1.png"))); // NOI18N
        jButtonAssento1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonAssento1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonAssento1MouseClicked(evt);
            }
        });

        jButtonAssento5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonAssento5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonAssento5MouseClicked(evt);
            }
        });

        jButtonAssento6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonAssento6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonAssento6MouseClicked(evt);
            }
        });

        jButtonAssento10.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonAssento10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonAssento10MouseClicked(evt);
            }
        });

        jButtonAssento9.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonAssento9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonAssento9MouseClicked(evt);
            }
        });

        jButtonAssento13.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonAssento13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonAssento13MouseClicked(evt);
            }
        });

        jButtonAssento14.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonAssento14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonAssento14MouseClicked(evt);
            }
        });

        jButtonAssento18.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonAssento18.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonAssento18MouseClicked(evt);
            }
        });

        jButtonAssento17.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonAssento17.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonAssento17MouseClicked(evt);
            }
        });

        jButtonAssento21.setToolTipText("");
        jButtonAssento21.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonAssento21.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonAssento21MouseClicked(evt);
            }
        });

        jButtonAssento22.setToolTipText("");
        jButtonAssento22.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonAssento22.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonAssento22MouseClicked(evt);
            }
        });

        jButtonAssento26.setToolTipText("");
        jButtonAssento26.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonAssento26.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonAssento26MouseClicked(evt);
            }
        });

        jButtonAssento25.setToolTipText("");
        jButtonAssento25.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonAssento25.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonAssento25MouseClicked(evt);
            }
        });

        jButtonAssento29.setToolTipText("");
        jButtonAssento29.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonAssento29.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonAssento29MouseClicked(evt);
            }
        });

        jButtonAssento30.setToolTipText("");
        jButtonAssento30.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonAssento30.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonAssento30MouseClicked(evt);
            }
        });

        jButtonAssento34.setToolTipText("");
        jButtonAssento34.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonAssento34.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonAssento34MouseClicked(evt);
            }
        });

        jButtonAssento33.setToolTipText("");
        jButtonAssento33.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonAssento33.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonAssento33MouseClicked(evt);
            }
        });

        jButtonAssento37.setToolTipText("");
        jButtonAssento37.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonAssento37.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonAssento37MouseClicked(evt);
            }
        });

        jButtonAssento38.setToolTipText("");
        jButtonAssento38.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonAssento38.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonAssento38MouseClicked(evt);
            }
        });

        jLabelOrigem.setForeground(new java.awt.Color(153, 153, 153));
        jLabelOrigem.setText("jLabel5");

        jLabelDestino.setForeground(new java.awt.Color(153, 153, 153));
        jLabelDestino.setText("jLabel5");

        jLabelHora.setForeground(new java.awt.Color(153, 153, 153));
        jLabelHora.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelHora.setText("jLabel5");

        jLabelQtd.setForeground(new java.awt.Color(153, 153, 153));
        jLabelQtd.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelQtd.setText("0");

        jButtonVoltarPrincipal.setBackground(new java.awt.Color(204, 204, 204));
        jButtonVoltarPrincipal.setForeground(new java.awt.Color(51, 51, 51));
        jButtonVoltarPrincipal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/bt_voltarprincipal.png"))); // NOI18N
        jButtonVoltarPrincipal.setBorder(null);
        jButtonVoltarPrincipal.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonVoltarPrincipal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonVoltarPrincipalMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanelWithBackground1Layout = new javax.swing.GroupLayout(jPanelWithBackground1);
        jPanelWithBackground1.setLayout(jPanelWithBackground1Layout);
        jPanelWithBackground1Layout.setHorizontalGroup(
            jPanelWithBackground1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelWithBackground1Layout.createSequentialGroup()
                .addGroup(jPanelWithBackground1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelWithBackground1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanelWithBackground1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabelOrigem, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanelWithBackground1Layout.createSequentialGroup()
                                .addGap(0, 2, Short.MAX_VALUE)
                                .addComponent(jLabel1)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelWithBackground1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabelDestino, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelWithBackground1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabelHora, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelWithBackground1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabelQtd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanelWithBackground1Layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(jPanelWithBackground1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelWithBackground1Layout.createSequentialGroup()
                                .addGroup(jPanelWithBackground1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButtonAssento2, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButtonAssento1, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanelWithBackground1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButtonAssento6, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButtonAssento5, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanelWithBackground1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButtonAssento10, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButtonAssento9, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanelWithBackground1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButtonAssento14, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButtonAssento13, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanelWithBackground1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButtonAssento18, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButtonAssento17, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanelWithBackground1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButtonAssento22, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButtonAssento21, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanelWithBackground1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButtonAssento26, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButtonAssento25, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanelWithBackground1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButtonAssento30, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButtonAssento29, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanelWithBackground1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButtonAssento34, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButtonAssento33, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanelWithBackground1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButtonAssento38, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButtonAssento37, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanelWithBackground1Layout.createSequentialGroup()
                                .addGroup(jPanelWithBackground1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButtonAssento3, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButtonAssento4, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanelWithBackground1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButtonAssento7, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButtonAssento8, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanelWithBackground1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButtonAssento11, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButtonAssento12, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanelWithBackground1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButtonAssento15, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButtonAssento16, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanelWithBackground1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButtonAssento19, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButtonAssento20, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanelWithBackground1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButtonAssento23, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButtonAssento24, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanelWithBackground1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButtonAssento27, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButtonAssento28, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanelWithBackground1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButtonAssento31, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButtonAssento32, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanelWithBackground1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButtonAssento35, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButtonAssento36, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanelWithBackground1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButtonAssento39, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButtonAssento40, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelWithBackground1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButtonVoltarPrincipal)
                .addGap(309, 309, 309))
        );
        jPanelWithBackground1Layout.setVerticalGroup(
            jPanelWithBackground1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelWithBackground1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelWithBackground1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelWithBackground1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelOrigem)
                    .addComponent(jLabelDestino)
                    .addComponent(jLabelHora)
                    .addComponent(jLabelQtd))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonVoltarPrincipal)
                .addGap(23, 23, 23)
                .addGroup(jPanelWithBackground1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelWithBackground1Layout.createSequentialGroup()
                        .addComponent(jButtonAssento3, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonAssento4, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelWithBackground1Layout.createSequentialGroup()
                        .addComponent(jButtonAssento7, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonAssento8, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelWithBackground1Layout.createSequentialGroup()
                        .addComponent(jButtonAssento11, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonAssento12, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelWithBackground1Layout.createSequentialGroup()
                        .addComponent(jButtonAssento15, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonAssento16, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelWithBackground1Layout.createSequentialGroup()
                        .addComponent(jButtonAssento19, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonAssento20, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelWithBackground1Layout.createSequentialGroup()
                        .addComponent(jButtonAssento23, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonAssento24, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelWithBackground1Layout.createSequentialGroup()
                        .addComponent(jButtonAssento27, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonAssento28, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelWithBackground1Layout.createSequentialGroup()
                        .addComponent(jButtonAssento31, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonAssento32, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelWithBackground1Layout.createSequentialGroup()
                        .addComponent(jButtonAssento35, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonAssento36, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelWithBackground1Layout.createSequentialGroup()
                        .addComponent(jButtonAssento39, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonAssento40, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(27, 27, 27)
                .addGroup(jPanelWithBackground1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelWithBackground1Layout.createSequentialGroup()
                        .addComponent(jButtonAssento2, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonAssento1, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelWithBackground1Layout.createSequentialGroup()
                        .addComponent(jButtonAssento6, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonAssento5, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelWithBackground1Layout.createSequentialGroup()
                        .addComponent(jButtonAssento10, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonAssento9, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelWithBackground1Layout.createSequentialGroup()
                        .addComponent(jButtonAssento14, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonAssento13, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelWithBackground1Layout.createSequentialGroup()
                        .addComponent(jButtonAssento18, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonAssento17, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelWithBackground1Layout.createSequentialGroup()
                        .addComponent(jButtonAssento22, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonAssento21, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelWithBackground1Layout.createSequentialGroup()
                        .addComponent(jButtonAssento26, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonAssento25, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelWithBackground1Layout.createSequentialGroup()
                        .addComponent(jButtonAssento30, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonAssento29, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelWithBackground1Layout.createSequentialGroup()
                        .addComponent(jButtonAssento34, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonAssento33, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelWithBackground1Layout.createSequentialGroup()
                        .addComponent(jButtonAssento38, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonAssento37, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(82, Short.MAX_VALUE))
        );

        jMenu3.setText("Gerenciar");

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem2.setText("Operadores");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem2);

        jMenuItem8.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem8.setText("Principal");
        jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem8ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem8);

        jMenuItem4.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem4.setText("Rotas");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem4);

        jMenuBar1.add(jMenu3);

        jMenu4.setText("Ajuda");

        jMenuItem6.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_T, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem6.setText("Trocar Operador");
        jMenu4.add(jMenuItem6);

        jMenuItem5.setText("Sobre");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem5);

        jMenuItem7.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_X, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem7.setText("Sair");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem7);

        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanelWithBackground1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanelWithBackground1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jButtonVoltarPrincipalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonVoltarPrincipalMouseClicked
         TelaInicio t = new TelaInicio();
         t.setVisible(true);
         this.setVisible(false);
    }//GEN-LAST:event_jButtonVoltarPrincipalMouseClicked

    private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed
         TelaInicio t = new TelaInicio();
         t.setVisible(true);
         this.setVisible(false);
    }//GEN-LAST:event_jMenuItem8ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        TelaNovaRota r = new TelaNovaRota();
        r.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
       this.setVisible(false);
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void jButtonAssento3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonAssento3MouseClicked
        addPassageiro(3);
    }//GEN-LAST:event_jButtonAssento3MouseClicked

    private void jButtonAssento4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonAssento4MouseClicked
        addPassageiro(4);
    }//GEN-LAST:event_jButtonAssento4MouseClicked

    private void jButtonAssento2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonAssento2MouseClicked
        addPassageiro(2);
    }//GEN-LAST:event_jButtonAssento2MouseClicked

    private void jButtonAssento1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonAssento1MouseClicked
        addPassageiro(1);
    }//GEN-LAST:event_jButtonAssento1MouseClicked

    private void jButtonAssento5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonAssento5MouseClicked
        addPassageiro(5);
    }//GEN-LAST:event_jButtonAssento5MouseClicked

    private void jButtonAssento6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonAssento6MouseClicked
        addPassageiro(6);
    }//GEN-LAST:event_jButtonAssento6MouseClicked

    private void jButtonAssento8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonAssento8MouseClicked
        addPassageiro(8);
    }//GEN-LAST:event_jButtonAssento8MouseClicked

    private void jButtonAssento7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonAssento7MouseClicked
        addPassageiro(7);
    }//GEN-LAST:event_jButtonAssento7MouseClicked

    private void jButtonAssento9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonAssento9MouseClicked
        addPassageiro(9);
    }//GEN-LAST:event_jButtonAssento9MouseClicked

    private void jButtonAssento10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonAssento10MouseClicked
        addPassageiro(10);
    }//GEN-LAST:event_jButtonAssento10MouseClicked

    private void jButtonAssento12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonAssento12MouseClicked
        addPassageiro(12);
    }//GEN-LAST:event_jButtonAssento12MouseClicked

    private void jButtonAssento11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonAssento11MouseClicked
        addPassageiro(11);
    }//GEN-LAST:event_jButtonAssento11MouseClicked

    private void jButtonAssento13MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonAssento13MouseClicked
        addPassageiro(13);
    }//GEN-LAST:event_jButtonAssento13MouseClicked

    private void jButtonAssento14MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonAssento14MouseClicked
        addPassageiro(14);
    }//GEN-LAST:event_jButtonAssento14MouseClicked

    private void jButtonAssento16MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonAssento16MouseClicked
        addPassageiro(16);
    }//GEN-LAST:event_jButtonAssento16MouseClicked

    private void jButtonAssento15MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonAssento15MouseClicked
        addPassageiro(15);
    }//GEN-LAST:event_jButtonAssento15MouseClicked

    private void jButtonAssento17MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonAssento17MouseClicked
        addPassageiro(17);
    }//GEN-LAST:event_jButtonAssento17MouseClicked

    private void jButtonAssento18MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonAssento18MouseClicked
        addPassageiro(18);
    }//GEN-LAST:event_jButtonAssento18MouseClicked

    private void jButtonAssento20MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonAssento20MouseClicked
        addPassageiro(20);
    }//GEN-LAST:event_jButtonAssento20MouseClicked

    private void jButtonAssento19MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonAssento19MouseClicked
        addPassageiro(19);
    }//GEN-LAST:event_jButtonAssento19MouseClicked

    private void jButtonAssento21MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonAssento21MouseClicked
        addPassageiro(21);
    }//GEN-LAST:event_jButtonAssento21MouseClicked

    private void jButtonAssento22MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonAssento22MouseClicked
        addPassageiro(22);
    }//GEN-LAST:event_jButtonAssento22MouseClicked

    private void jButtonAssento24MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonAssento24MouseClicked
        addPassageiro(24);
    }//GEN-LAST:event_jButtonAssento24MouseClicked

    private void jButtonAssento23MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonAssento23MouseClicked
        addPassageiro(23);
    }//GEN-LAST:event_jButtonAssento23MouseClicked

    private void jButtonAssento25MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonAssento25MouseClicked
        addPassageiro(25);
    }//GEN-LAST:event_jButtonAssento25MouseClicked

    private void jButtonAssento26MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonAssento26MouseClicked
        addPassageiro(26);
    }//GEN-LAST:event_jButtonAssento26MouseClicked

    private void jButtonAssento28MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonAssento28MouseClicked
        addPassageiro(28);
    }//GEN-LAST:event_jButtonAssento28MouseClicked

    private void jButtonAssento27MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonAssento27MouseClicked
        addPassageiro(27);
    }//GEN-LAST:event_jButtonAssento27MouseClicked

    private void jButtonAssento29MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonAssento29MouseClicked
        addPassageiro(29);
    }//GEN-LAST:event_jButtonAssento29MouseClicked

    private void jButtonAssento30MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonAssento30MouseClicked
        addPassageiro(30);
    }//GEN-LAST:event_jButtonAssento30MouseClicked

    private void jButtonAssento32MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonAssento32MouseClicked
        addPassageiro(32);
    }//GEN-LAST:event_jButtonAssento32MouseClicked

    private void jButtonAssento31MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonAssento31MouseClicked
        addPassageiro(31);
    }//GEN-LAST:event_jButtonAssento31MouseClicked

    private void jButtonAssento33MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonAssento33MouseClicked
        addPassageiro(33);
    }//GEN-LAST:event_jButtonAssento33MouseClicked

    private void jButtonAssento34MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonAssento34MouseClicked
        addPassageiro(34);
    }//GEN-LAST:event_jButtonAssento34MouseClicked

    private void jButtonAssento36MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonAssento36MouseClicked
        addPassageiro(36);
    }//GEN-LAST:event_jButtonAssento36MouseClicked

    private void jButtonAssento35MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonAssento35MouseClicked
        addPassageiro(35);
    }//GEN-LAST:event_jButtonAssento35MouseClicked

    private void jButtonAssento37MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonAssento37MouseClicked
        addPassageiro(37);
    }//GEN-LAST:event_jButtonAssento37MouseClicked

    private void jButtonAssento38MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonAssento38MouseClicked
        addPassageiro(38);
    }//GEN-LAST:event_jButtonAssento38MouseClicked

    private void jButtonAssento40MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonAssento40MouseClicked
        addPassageiro(40);
    }//GEN-LAST:event_jButtonAssento40MouseClicked

    private void jButtonAssento39MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonAssento39MouseClicked
        addPassageiro(39);
    }//GEN-LAST:event_jButtonAssento39MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaDetalheOnibus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaDetalheOnibus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaDetalheOnibus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaDetalheOnibus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new TelaDetalheOnibus().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAssento1;
    private javax.swing.JButton jButtonAssento10;
    private javax.swing.JButton jButtonAssento11;
    private javax.swing.JButton jButtonAssento12;
    private javax.swing.JButton jButtonAssento13;
    private javax.swing.JButton jButtonAssento14;
    private javax.swing.JButton jButtonAssento15;
    private javax.swing.JButton jButtonAssento16;
    private javax.swing.JButton jButtonAssento17;
    private javax.swing.JButton jButtonAssento18;
    private javax.swing.JButton jButtonAssento19;
    private javax.swing.JButton jButtonAssento2;
    private javax.swing.JButton jButtonAssento20;
    private javax.swing.JButton jButtonAssento21;
    private javax.swing.JButton jButtonAssento22;
    private javax.swing.JButton jButtonAssento23;
    private javax.swing.JButton jButtonAssento24;
    private javax.swing.JButton jButtonAssento25;
    private javax.swing.JButton jButtonAssento26;
    private javax.swing.JButton jButtonAssento27;
    private javax.swing.JButton jButtonAssento28;
    private javax.swing.JButton jButtonAssento29;
    private javax.swing.JButton jButtonAssento3;
    private javax.swing.JButton jButtonAssento30;
    private javax.swing.JButton jButtonAssento31;
    private javax.swing.JButton jButtonAssento32;
    private javax.swing.JButton jButtonAssento33;
    private javax.swing.JButton jButtonAssento34;
    private javax.swing.JButton jButtonAssento35;
    private javax.swing.JButton jButtonAssento36;
    private javax.swing.JButton jButtonAssento37;
    private javax.swing.JButton jButtonAssento38;
    private javax.swing.JButton jButtonAssento39;
    private javax.swing.JButton jButtonAssento4;
    private javax.swing.JButton jButtonAssento40;
    private javax.swing.JButton jButtonAssento5;
    private javax.swing.JButton jButtonAssento6;
    private javax.swing.JButton jButtonAssento7;
    private javax.swing.JButton jButtonAssento8;
    private javax.swing.JButton jButtonAssento9;
    private javax.swing.JButton jButtonVoltarPrincipal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabelDestino;
    private javax.swing.JLabel jLabelHora;
    private javax.swing.JLabel jLabelOrigem;
    private javax.swing.JLabel jLabelQtd;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private view.JPanelWithBackground jPanelWithBackground1;
    // End of variables declaration//GEN-END:variables

    public void geraImgArrayAssentos(){
        RotaIndexControler ind = new RotaIndexControler();
        int index = RotaIndexControler.getIndex();
        JButton jButtonAssento[] = new JButton[41];
        jButtonAssento[1]  = jButtonAssento1;
        jButtonAssento[2]  = jButtonAssento2;
        jButtonAssento[3]  = jButtonAssento3;
        jButtonAssento[4]  = jButtonAssento4;
        jButtonAssento[5]  = jButtonAssento5;
        jButtonAssento[6]  = jButtonAssento6;
        jButtonAssento[7]  = jButtonAssento7;
        jButtonAssento[8]  = jButtonAssento8;
        jButtonAssento[9]  = jButtonAssento9;
        jButtonAssento[10] = jButtonAssento10;
        jButtonAssento[11] = jButtonAssento11;
        jButtonAssento[12] = jButtonAssento12;
        jButtonAssento[13] = jButtonAssento13;
        jButtonAssento[14] = jButtonAssento14;
        jButtonAssento[15] = jButtonAssento15;
        jButtonAssento[16] = jButtonAssento16;
        jButtonAssento[17] = jButtonAssento17;
        jButtonAssento[18] = jButtonAssento18;
        jButtonAssento[19] = jButtonAssento19;
        jButtonAssento[20] = jButtonAssento20;
        jButtonAssento[21] = jButtonAssento21;
        jButtonAssento[22] = jButtonAssento22;
        jButtonAssento[23] = jButtonAssento23;
        jButtonAssento[24] = jButtonAssento24;
        jButtonAssento[25] = jButtonAssento25;
        jButtonAssento[26] = jButtonAssento26;
        jButtonAssento[27] = jButtonAssento27;
        jButtonAssento[28] = jButtonAssento28;
        jButtonAssento[29] = jButtonAssento29;
        jButtonAssento[30] = jButtonAssento30;
        jButtonAssento[31] = jButtonAssento31;
        jButtonAssento[32] = jButtonAssento32;
        jButtonAssento[33] = jButtonAssento33;
        jButtonAssento[34] = jButtonAssento34;
        jButtonAssento[35] = jButtonAssento35;
        jButtonAssento[36] = jButtonAssento36;
        jButtonAssento[37] = jButtonAssento37;
        jButtonAssento[38] = jButtonAssento38;
        jButtonAssento[39] = jButtonAssento39;
        jButtonAssento[40] = jButtonAssento40;
        for(int i=1;i<=40;i++){
            if(Repositorio.getRotas().get(index).verificaAssento(i) == "vazio"){
                jButtonAssento[i].setIcon(new ImageIcon("src/view/bg_ass_livre_"+i+".png"));
            }else{
               jButtonAssento[i].setIcon(new ImageIcon("src/view/bg_ass_ocupado_"+i+".png"));
                Cliente c = new Cliente();
                c.setNome(Repositorio.getRotas().get(index).verificaAssento(i));
                Repositorio.getClientes().add(c);
            }
        }
    }
    
    public void addPassageiro(int assento){
        RotaIndexControler ind = new RotaIndexControler();
        int index = RotaIndexControler.getIndex();
        RotaIndexControler.setNumAssento(assento);
        if(Repositorio.getRotas().get(index).verificaAssento(assento) == "vazio"){
                TelaNovoCliente c = new TelaNovoCliente();
                c.setVisible(true);
                this.setVisible(false);
            }else{
                TelaExcluiCliente x = new TelaExcluiCliente();
                x.setVisible(true);
                this.setVisible(false);
            }
        
    }

}
