package view;


import java.awt.Color;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;
import model.*;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author informatica
 */
public class TelaExcluiCliente extends javax.swing.JFrame{

    /**
     * Creates new form Principal
     */
    public TelaExcluiCliente() {
        initComponents();
        
        RotaIndexControler ind = new RotaIndexControler();
        int index = RotaIndexControler.getIndex();
        int assen = RotaIndexControler.getNumAssento();
        if(assen<10){
            jLabelNumAssento.setText("0"+assen);
        }else{
            jLabelNumAssento.setText(""+assen);
        } 
        String dadosPassageiro = Repositorio.getRotas().get(index).verificaAssento(assen);
        String s[] = dadosPassageiro.split("-");
        jLabelNome.setText(s[0]);
        jLabelCpf.setText(s[1]);
        jLabelTele.setText(s[2]);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jPanelWithBackground1 = new view.JPanelWithBackground("C:/Users/Jeferson/Documents/NetBeansProjects/GetBus/src/view/bg_novocliente.png");//("C:/Documents and Settings/informatica/Meus documentos/NetBeansProjects/GetBus/src/view/bg_inicio.png");
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButtonVoltarOnibus = new javax.swing.JButton();
        jButtonRemoveCliente = new javax.swing.JButton();
        jLabelNumAssento = new javax.swing.JLabel();
        jLabelNome = new javax.swing.JLabel();
        jLabelCpf = new javax.swing.JLabel();
        jLabelTele = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jMenuItemOperadores = new javax.swing.JMenuItem();
        jMenuItemPrincipal = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuItemLogout = new javax.swing.JMenuItem();
        jMenuItemSobre = new javax.swing.JMenuItem();
        jMenuItemSair = new javax.swing.JMenuItem();

        jMenu1.setText("jMenu1");

        jMenu2.setText("jMenu2");

        jMenuItem1.setText("jMenuItem1");

        jMenuItem3.setText("jMenuItem3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("GetBus - Adicionar Passageiro");
        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(800, 500));
        setResizable(false);

        jPanelWithBackground1.setMaximumSize(new java.awt.Dimension(800, 500));
        jPanelWithBackground1.setMinimumSize(new java.awt.Dimension(800, 500));
        jPanelWithBackground1.setPreferredSize(new java.awt.Dimension(800, 500));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/label_cpf.png"))); // NOI18N

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/label_fone.png"))); // NOI18N

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/label_nome.png"))); // NOI18N

        jButtonVoltarOnibus.setBackground(new java.awt.Color(204, 204, 204));
        jButtonVoltarOnibus.setForeground(new java.awt.Color(51, 51, 51));
        jButtonVoltarOnibus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/bt_voltarota.png"))); // NOI18N
        jButtonVoltarOnibus.setBorder(null);
        jButtonVoltarOnibus.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonVoltarOnibus.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonVoltarOnibusMouseClicked(evt);
            }
        });
        jButtonVoltarOnibus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVoltarOnibusActionPerformed(evt);
            }
        });

        jButtonRemoveCliente.setBackground(new java.awt.Color(204, 204, 204));
        jButtonRemoveCliente.setForeground(new java.awt.Color(51, 51, 51));
        jButtonRemoveCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/bt_excliente.png"))); // NOI18N
        jButtonRemoveCliente.setBorder(null);
        jButtonRemoveCliente.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonRemoveCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonRemoveClienteMouseClicked(evt);
            }
        });
        jButtonRemoveCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRemoveClienteActionPerformed(evt);
            }
        });

        jLabelNumAssento.setFont(new java.awt.Font("Tahoma", 0, 180)); // NOI18N
        jLabelNumAssento.setForeground(new java.awt.Color(102, 102, 102));
        jLabelNumAssento.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelNumAssento.setText("01");

        jLabelNome.setForeground(new java.awt.Color(102, 102, 102));
        jLabelNome.setText("jLabel1");

        jLabelCpf.setForeground(new java.awt.Color(102, 102, 102));
        jLabelCpf.setText("jLabel1");

        jLabelTele.setForeground(new java.awt.Color(102, 102, 102));
        jLabelTele.setText("jLabel1");

        javax.swing.GroupLayout jPanelWithBackground1Layout = new javax.swing.GroupLayout(jPanelWithBackground1);
        jPanelWithBackground1.setLayout(jPanelWithBackground1Layout);
        jPanelWithBackground1Layout.setHorizontalGroup(
            jPanelWithBackground1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelWithBackground1Layout.createSequentialGroup()
                .addGroup(jPanelWithBackground1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanelWithBackground1Layout.createSequentialGroup()
                        .addGap(0, 10, Short.MAX_VALUE)
                        .addGroup(jPanelWithBackground1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelWithBackground1Layout.createSequentialGroup()
                                .addGap(50, 50, 50)
                                .addGroup(jPanelWithBackground1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButtonRemoveCliente)
                                    .addComponent(jButtonVoltarOnibus)))
                            .addGroup(jPanelWithBackground1Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jLabelCpf, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanelWithBackground1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanelWithBackground1Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jLabelTele, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanelWithBackground1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabelNome, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(148, 148, 148)
                .addComponent(jLabelNumAssento, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(132, 132, 132))
        );
        jPanelWithBackground1Layout.setVerticalGroup(
            jPanelWithBackground1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelWithBackground1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelNome)
                .addGap(36, 36, 36)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelCpf)
                .addGap(36, 36, 36)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelTele)
                .addGap(45, 45, 45)
                .addComponent(jButtonRemoveCliente)
                .addGap(18, 18, 18)
                .addComponent(jButtonVoltarOnibus)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelWithBackground1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelNumAssento, javax.swing.GroupLayout.DEFAULT_SIZE, 456, Short.MAX_VALUE)
                .addGap(44, 44, 44))
        );

        jMenu3.setText("Gerenciar");

        jMenuItemOperadores.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItemOperadores.setText("Operadores");
        jMenuItemOperadores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemOperadoresActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItemOperadores);

        jMenuItemPrincipal.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItemPrincipal.setText("Principal");
        jMenuItemPrincipal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemPrincipalActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItemPrincipal);

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem2.setText("Rota");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem2);

        jMenuBar1.add(jMenu3);

        jMenu4.setText("Ajuda");

        jMenuItemLogout.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_T, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItemLogout.setText("Trocar Operador");
        jMenu4.add(jMenuItemLogout);

        jMenuItemSobre.setText("Sobre");
        jMenuItemSobre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemSobreActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItemSobre);

        jMenuItemSair.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_X, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItemSair.setText("Sair");
        jMenuItemSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemSairActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItemSair);

        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanelWithBackground1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 3, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelWithBackground1, javax.swing.GroupLayout.DEFAULT_SIZE, 511, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemOperadoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemOperadoresActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItemOperadoresActionPerformed

    private void jMenuItemSobreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemSobreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItemSobreActionPerformed

    private void jButtonVoltarOnibusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVoltarOnibusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonVoltarOnibusActionPerformed

    private void jButtonRemoveClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRemoveClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonRemoveClienteActionPerformed

    private void jButtonRemoveClienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonRemoveClienteMouseClicked
        RotaIndexControler ind = new RotaIndexControler();
        int index = RotaIndexControler.getIndex();
        int assen = RotaIndexControler.getNumAssento();
            Repositorio.getRotas().get(index).gerenciaPassageiro(assen);
            TelaDetalheOnibus d = new TelaDetalheOnibus();
            d.setVisible(true);
            this.setVisible(false);
    }//GEN-LAST:event_jButtonRemoveClienteMouseClicked

    private void jMenuItemPrincipalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemPrincipalActionPerformed
         TelaInicio t = new TelaInicio();
         t.setVisible(true);
         this.setVisible(false);
    }//GEN-LAST:event_jMenuItemPrincipalActionPerformed

    private void jButtonVoltarOnibusMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonVoltarOnibusMouseClicked
        TelaDetalheOnibus d = new TelaDetalheOnibus();
        d.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButtonVoltarOnibusMouseClicked

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        TelaNovaRota r = new TelaNovaRota();
        r.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItemSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemSairActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_jMenuItemSairActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaExcluiCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaExcluiCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaExcluiCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaExcluiCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new TelaExcluiCliente().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonRemoveCliente;
    private javax.swing.JButton jButtonVoltarOnibus;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabelCpf;
    private javax.swing.JLabel jLabelNome;
    private javax.swing.JLabel jLabelNumAssento;
    private javax.swing.JLabel jLabelTele;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItemLogout;
    private javax.swing.JMenuItem jMenuItemOperadores;
    private javax.swing.JMenuItem jMenuItemPrincipal;
    private javax.swing.JMenuItem jMenuItemSair;
    private javax.swing.JMenuItem jMenuItemSobre;
    private view.JPanelWithBackground jPanelWithBackground1;
    // End of variables declaration//GEN-END:variables
}

